# This action checks out the commit that triggered the action and runs standardjs --fix
# Then if changes were made, it commits those changes
# If there are linting errors that it couldn't fix it exits with a failure
# otherwise it exists with success

name: linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup node # Allows us to run npx command
        uses: actions/setup-node@v2
        # Now you can just run eslint or standard yourself
      - name: Runs standard-js and tries to automatically fix issues
        id: standard-fix
        run: |
          npx standard --fix || true
          git diff --exit-code
          echo "::set-output name=has_changes::$?"
      - name: Commit files
        id: commit
        # git diff sets exit code to 1 if there are differences
        if: steps.standard-fix.outputs.has_changes == '1' 
        continue-on-error: true
        run: |
          git add .
          git commit -m "${{ github.event.pull_request.head.ref }} Automatic standard --fix"
      - name: Push changes
        if: steps.commit.outcome == 'success' && steps.standard-fix.outputs.has_changes == '1'
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}
