# This action checks out the commit that triggered the action and runs standardjs
# If there are linting errors it exits with a failure
# otherwise it exists with success

name: linter

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for the 'not_main' branch
  pull_request:
    branches: [ not_main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup node # Allows us to run npx command
        uses: actions/setup-node@v2
        # Now you can just run eslint or standard yourself
      - name: StandardJS lint checks
        run: npx standard

